# Generated by Django 6.0.5 on 2026-05-06 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about_alter_contact_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='about',
            name='bio',
            field=models.TextField(default='I build professional web applications using Python & Django.'),
        ),
        migrations.AlterField(
            model_name='about',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.EmailField(default='dad@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='about',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='location',
            field=models.CharField(default='Pakistan', max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(default='Dad Mohammad', max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.CharField(default='+92 XXX XXXXXXX', max_length=20),
        ),
        migrations.AlterField(
            model_name='about',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(default='Full Stack Django Developer', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(help_text='e.g., Python, Django, Bootstrap', max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('tools', 'Tools & DevOps')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
