# Generated by Django 6.0.5 on 2026-05-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contactmessage_delete_contact_alter_about_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
